### ISSUE TITLE
No restriction in course activities

### ISSUE THREAD

**Issue by Fmarra** [ewallah/moodle-availability_condition_language#4]
Hi Renaat, thanks for this plugin it is really great!
I can filter the activities by language in front page and customize the visualization of my users.

I have issues with adding the restriction in the courses activities (first screenshot). I simply don't see the restriction by language option as in the front page activities (second screenshot).
![restricted_access_in_courses_activities](https://cloud.githubusercontent.com/assets/11939269/7394430/c7ea6836-ee93-11e4-89d2-3774c28a6317.png)

![restricted_access_in_front_page](https://cloud.githubusercontent.com/assets/11939269/7394434/cc962492-ee93-11e4-9149-c2d5d5bac0e1.png)

**Comment by ewallah** [comment]
Hi Fmara,

there are 2 reasons why it is possible that the restriction does not show:
* There is only 1 language installed in the system (obvious, we need a least 2 languages installed to restrict)
* The course language is forced. (Course - Edit settings - Appearance - Force language). When a course has a forced language, everything appears in that forced language and we are certain no user will ever arrive with another language enabled.  On this moment there is no need to show the restriction as it would only create the illusion that people could be restricted.


Greetings

**Comment by Fmarra** [comment]
Hi! Super thanks for your answer! 
Yes, indeed we had the forced language in the course I was trying to add the language restriction to. I set up to "Do not force" and now I see the Language among the restriction criteria.

**Comment by mlhamilton** [comment]
PLEASE PLEASE PLEASE place the comment above on the Moodle Plugins page:
https://moodle.org/plugins/availability_language

"There is only 1 language installed in the system (obvious, we need a least 2 languages installed to restrict)
The course language is forced. (Course - Edit settings - Appearance - Force language). When a course has a forced language, everything appears in that forced language and we are certain no user will ever arrive with another language enabled. On this moment there is no need to show the restriction as it would only create the illusion that people could be restricted."
